

.PHONY : TARGET0
TARGET0 :
	@cd /home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.d.h_b1-01.S/dut; riscv32-unknown-elf-gcc -march=rv32ifd_zicsr_zfh          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/pager/Desktop/work/ZfhTest/spike/env/link.ld         -I /home/pager/Desktop/work/ZfhTest/spike/env/         -I /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/env /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/rv32i_m/Zfh/src/fcvt.d.h_b1-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -DFLEN=64 -mabi=ilp32 ; spike --isa=rv32ifd_Zicsr_Zfh +signature=/home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.d.h_b1-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET1
TARGET1 :
	@cd /home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.d.h_b22-01.S/dut; riscv32-unknown-elf-gcc -march=rv32ifd_zicsr_zfh          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/pager/Desktop/work/ZfhTest/spike/env/link.ld         -I /home/pager/Desktop/work/ZfhTest/spike/env/         -I /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/env /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/rv32i_m/Zfh/src/fcvt.d.h_b22-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -DFLEN=64 -mabi=ilp32 ; spike --isa=rv32ifd_Zicsr_Zfh +signature=/home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.d.h_b22-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET2
TARGET2 :
	@cd /home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.d.h_b23-01.S/dut; riscv32-unknown-elf-gcc -march=rv32ifd_zicsr_zfh          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/pager/Desktop/work/ZfhTest/spike/env/link.ld         -I /home/pager/Desktop/work/ZfhTest/spike/env/         -I /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/env /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/rv32i_m/Zfh/src/fcvt.d.h_b23-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -DFLEN=64 -mabi=ilp32 ; spike --isa=rv32ifd_Zicsr_Zfh +signature=/home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.d.h_b23-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET3
TARGET3 :
	@cd /home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.d.h_b24-01.S/dut; riscv32-unknown-elf-gcc -march=rv32ifd_zicsr_zfh          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/pager/Desktop/work/ZfhTest/spike/env/link.ld         -I /home/pager/Desktop/work/ZfhTest/spike/env/         -I /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/env /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/rv32i_m/Zfh/src/fcvt.d.h_b24-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -DFLEN=64 -mabi=ilp32 ; spike --isa=rv32ifd_Zicsr_Zfh +signature=/home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.d.h_b24-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET4
TARGET4 :
	@cd /home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.d.h_b27-01.S/dut; riscv32-unknown-elf-gcc -march=rv32ifd_zicsr_zfh          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/pager/Desktop/work/ZfhTest/spike/env/link.ld         -I /home/pager/Desktop/work/ZfhTest/spike/env/         -I /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/env /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/rv32i_m/Zfh/src/fcvt.d.h_b27-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -DFLEN=64 -mabi=ilp32 ; spike --isa=rv32ifd_Zicsr_Zfh +signature=/home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.d.h_b27-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET5
TARGET5 :
	@cd /home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.d.h_b28-01.S/dut; riscv32-unknown-elf-gcc -march=rv32ifd_zicsr_zfh          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/pager/Desktop/work/ZfhTest/spike/env/link.ld         -I /home/pager/Desktop/work/ZfhTest/spike/env/         -I /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/env /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/rv32i_m/Zfh/src/fcvt.d.h_b28-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -DFLEN=64 -mabi=ilp32 ; spike --isa=rv32ifd_Zicsr_Zfh +signature=/home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.d.h_b28-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET6
TARGET6 :
	@cd /home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.d.h_b29-01.S/dut; riscv32-unknown-elf-gcc -march=rv32ifd_zicsr_zfh          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/pager/Desktop/work/ZfhTest/spike/env/link.ld         -I /home/pager/Desktop/work/ZfhTest/spike/env/         -I /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/env /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/rv32i_m/Zfh/src/fcvt.d.h_b29-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -DFLEN=64 -mabi=ilp32 ; spike --isa=rv32ifd_Zicsr_Zfh +signature=/home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.d.h_b29-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET7
TARGET7 :
	@cd /home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.h.d_b1-01.S/dut; riscv32-unknown-elf-gcc -march=rv32ifd_zicsr_zfh          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/pager/Desktop/work/ZfhTest/spike/env/link.ld         -I /home/pager/Desktop/work/ZfhTest/spike/env/         -I /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/env /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/rv32i_m/Zfh/src/fcvt.h.d_b1-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -DFLEN=64 -mabi=ilp32 ; spike --isa=rv32ifd_Zicsr_Zfh +signature=/home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.h.d_b1-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET8
TARGET8 :
	@cd /home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.h.d_b22-01.S/dut; riscv32-unknown-elf-gcc -march=rv32ifd_zicsr_zfh          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/pager/Desktop/work/ZfhTest/spike/env/link.ld         -I /home/pager/Desktop/work/ZfhTest/spike/env/         -I /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/env /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/rv32i_m/Zfh/src/fcvt.h.d_b22-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -DFLEN=64 -mabi=ilp32 ; spike --isa=rv32ifd_Zicsr_Zfh +signature=/home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.h.d_b22-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET9
TARGET9 :
	@cd /home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.h.d_b23-01.S/dut; riscv32-unknown-elf-gcc -march=rv32ifd_zicsr_zfh          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/pager/Desktop/work/ZfhTest/spike/env/link.ld         -I /home/pager/Desktop/work/ZfhTest/spike/env/         -I /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/env /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/rv32i_m/Zfh/src/fcvt.h.d_b23-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -DFLEN=64 -mabi=ilp32 ; spike --isa=rv32ifd_Zicsr_Zfh +signature=/home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.h.d_b23-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET10
TARGET10 :
	@cd /home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.h.d_b24-01.S/dut; riscv32-unknown-elf-gcc -march=rv32ifd_zicsr_zfh          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/pager/Desktop/work/ZfhTest/spike/env/link.ld         -I /home/pager/Desktop/work/ZfhTest/spike/env/         -I /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/env /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/rv32i_m/Zfh/src/fcvt.h.d_b24-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -DFLEN=64 -mabi=ilp32 ; spike --isa=rv32ifd_Zicsr_Zfh +signature=/home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.h.d_b24-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET11
TARGET11 :
	@cd /home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.h.d_b27-01.S/dut; riscv32-unknown-elf-gcc -march=rv32ifd_zicsr_zfh          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/pager/Desktop/work/ZfhTest/spike/env/link.ld         -I /home/pager/Desktop/work/ZfhTest/spike/env/         -I /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/env /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/rv32i_m/Zfh/src/fcvt.h.d_b27-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -DFLEN=64 -mabi=ilp32 ; spike --isa=rv32ifd_Zicsr_Zfh +signature=/home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.h.d_b27-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET12
TARGET12 :
	@cd /home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.h.d_b28-01.S/dut; riscv32-unknown-elf-gcc -march=rv32ifd_zicsr_zfh          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/pager/Desktop/work/ZfhTest/spike/env/link.ld         -I /home/pager/Desktop/work/ZfhTest/spike/env/         -I /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/env /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/rv32i_m/Zfh/src/fcvt.h.d_b28-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -DFLEN=64 -mabi=ilp32 ; spike --isa=rv32ifd_Zicsr_Zfh +signature=/home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.h.d_b28-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET13
TARGET13 :
	@cd /home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.h.d_b29-01.S/dut; riscv32-unknown-elf-gcc -march=rv32ifd_zicsr_zfh          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/pager/Desktop/work/ZfhTest/spike/env/link.ld         -I /home/pager/Desktop/work/ZfhTest/spike/env/         -I /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/env /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/rv32i_m/Zfh/src/fcvt.h.d_b29-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -DFLEN=64 -mabi=ilp32 ; spike --isa=rv32ifd_Zicsr_Zfh +signature=/home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.h.d_b29-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET14
TARGET14 :
	@cd /home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.h.s_b1-01.S/dut; riscv32-unknown-elf-gcc -march=rv32if_zicsr_zfh          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/pager/Desktop/work/ZfhTest/spike/env/link.ld         -I /home/pager/Desktop/work/ZfhTest/spike/env/         -I /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/env /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/rv32i_m/Zfh/src/fcvt.h.s_b1-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -DFLEN=32 -mabi=ilp32 ; spike --isa=rv32ifd_Zicsr_Zfh +signature=/home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.h.s_b1-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET15
TARGET15 :
	@cd /home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.h.s_b22-01.S/dut; riscv32-unknown-elf-gcc -march=rv32if_zicsr_zfh          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/pager/Desktop/work/ZfhTest/spike/env/link.ld         -I /home/pager/Desktop/work/ZfhTest/spike/env/         -I /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/env /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/rv32i_m/Zfh/src/fcvt.h.s_b22-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -DFLEN=32 -mabi=ilp32 ; spike --isa=rv32ifd_Zicsr_Zfh +signature=/home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.h.s_b22-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET16
TARGET16 :
	@cd /home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.h.s_b23-01.S/dut; riscv32-unknown-elf-gcc -march=rv32if_zicsr_zfh          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/pager/Desktop/work/ZfhTest/spike/env/link.ld         -I /home/pager/Desktop/work/ZfhTest/spike/env/         -I /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/env /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/rv32i_m/Zfh/src/fcvt.h.s_b23-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -DFLEN=32 -mabi=ilp32 ; spike --isa=rv32ifd_Zicsr_Zfh +signature=/home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.h.s_b23-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET17
TARGET17 :
	@cd /home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.h.s_b24-01.S/dut; riscv32-unknown-elf-gcc -march=rv32if_zicsr_zfh          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/pager/Desktop/work/ZfhTest/spike/env/link.ld         -I /home/pager/Desktop/work/ZfhTest/spike/env/         -I /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/env /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/rv32i_m/Zfh/src/fcvt.h.s_b24-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -DFLEN=32 -mabi=ilp32 ; spike --isa=rv32ifd_Zicsr_Zfh +signature=/home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.h.s_b24-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET18
TARGET18 :
	@cd /home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.h.s_b27-01.S/dut; riscv32-unknown-elf-gcc -march=rv32if_zicsr_zfh          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/pager/Desktop/work/ZfhTest/spike/env/link.ld         -I /home/pager/Desktop/work/ZfhTest/spike/env/         -I /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/env /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/rv32i_m/Zfh/src/fcvt.h.s_b27-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -DFLEN=32 -mabi=ilp32 ; spike --isa=rv32ifd_Zicsr_Zfh +signature=/home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.h.s_b27-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET19
TARGET19 :
	@cd /home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.h.s_b28-01.S/dut; riscv32-unknown-elf-gcc -march=rv32if_zicsr_zfh          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/pager/Desktop/work/ZfhTest/spike/env/link.ld         -I /home/pager/Desktop/work/ZfhTest/spike/env/         -I /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/env /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/rv32i_m/Zfh/src/fcvt.h.s_b28-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -DFLEN=32 -mabi=ilp32 ; spike --isa=rv32ifd_Zicsr_Zfh +signature=/home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.h.s_b28-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET20
TARGET20 :
	@cd /home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.h.s_b29-01.S/dut; riscv32-unknown-elf-gcc -march=rv32if_zicsr_zfh          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/pager/Desktop/work/ZfhTest/spike/env/link.ld         -I /home/pager/Desktop/work/ZfhTest/spike/env/         -I /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/env /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/rv32i_m/Zfh/src/fcvt.h.s_b29-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -DFLEN=32 -mabi=ilp32 ; spike --isa=rv32ifd_Zicsr_Zfh +signature=/home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.h.s_b29-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET21
TARGET21 :
	@cd /home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.s.h_b1-01.S/dut; riscv32-unknown-elf-gcc -march=rv32if_zicsr_zfh          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/pager/Desktop/work/ZfhTest/spike/env/link.ld         -I /home/pager/Desktop/work/ZfhTest/spike/env/         -I /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/env /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/rv32i_m/Zfh/src/fcvt.s.h_b1-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -DFLEN=32 -mabi=ilp32 ; spike --isa=rv32ifd_Zicsr_Zfh +signature=/home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.s.h_b1-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET22
TARGET22 :
	@cd /home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.s.h_b22-01.S/dut; riscv32-unknown-elf-gcc -march=rv32if_zicsr_zfh          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/pager/Desktop/work/ZfhTest/spike/env/link.ld         -I /home/pager/Desktop/work/ZfhTest/spike/env/         -I /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/env /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/rv32i_m/Zfh/src/fcvt.s.h_b22-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -DFLEN=32 -mabi=ilp32 ; spike --isa=rv32ifd_Zicsr_Zfh +signature=/home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.s.h_b22-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET23
TARGET23 :
	@cd /home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.s.h_b23-01.S/dut; riscv32-unknown-elf-gcc -march=rv32if_zicsr_zfh          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/pager/Desktop/work/ZfhTest/spike/env/link.ld         -I /home/pager/Desktop/work/ZfhTest/spike/env/         -I /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/env /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/rv32i_m/Zfh/src/fcvt.s.h_b23-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -DFLEN=32 -mabi=ilp32 ; spike --isa=rv32ifd_Zicsr_Zfh +signature=/home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.s.h_b23-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET24
TARGET24 :
	@cd /home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.s.h_b24-01.S/dut; riscv32-unknown-elf-gcc -march=rv32if_zicsr_zfh          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/pager/Desktop/work/ZfhTest/spike/env/link.ld         -I /home/pager/Desktop/work/ZfhTest/spike/env/         -I /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/env /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/rv32i_m/Zfh/src/fcvt.s.h_b24-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -DFLEN=32 -mabi=ilp32 ; spike --isa=rv32ifd_Zicsr_Zfh +signature=/home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.s.h_b24-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET25
TARGET25 :
	@cd /home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.s.h_b27-01.S/dut; riscv32-unknown-elf-gcc -march=rv32if_zicsr_zfh          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/pager/Desktop/work/ZfhTest/spike/env/link.ld         -I /home/pager/Desktop/work/ZfhTest/spike/env/         -I /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/env /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/rv32i_m/Zfh/src/fcvt.s.h_b27-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -DFLEN=32 -mabi=ilp32 ; spike --isa=rv32ifd_Zicsr_Zfh +signature=/home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.s.h_b27-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET26
TARGET26 :
	@cd /home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.s.h_b28-01.S/dut; riscv32-unknown-elf-gcc -march=rv32if_zicsr_zfh          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/pager/Desktop/work/ZfhTest/spike/env/link.ld         -I /home/pager/Desktop/work/ZfhTest/spike/env/         -I /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/env /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/rv32i_m/Zfh/src/fcvt.s.h_b28-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -DFLEN=32 -mabi=ilp32 ; spike --isa=rv32ifd_Zicsr_Zfh +signature=/home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.s.h_b28-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET27
TARGET27 :
	@cd /home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.s.h_b29-01.S/dut; riscv32-unknown-elf-gcc -march=rv32if_zicsr_zfh          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/pager/Desktop/work/ZfhTest/spike/env/link.ld         -I /home/pager/Desktop/work/ZfhTest/spike/env/         -I /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/env /home/pager/Desktop/work/ZfhTest/riscv-arch-test/riscv-test-suite/rv32i_m/Zfh/src/fcvt.s.h_b29-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -DFLEN=32 -mabi=ilp32 ; spike --isa=rv32ifd_Zicsr_Zfh +signature=/home/pager/Desktop/work/ZfhTest/riscof_work/rv32i_m/Zfh/src/fcvt.s.h_b29-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;